name: Formula E Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Requests
        run: pip install requests

      - name: Download latest Formula E calendar
        run: python scripts/update_formulae.py

      - name: Commit updated ICS
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add data/2026/formula-e.ics

          if ! git diff --cached --quiet; then
            git commit -m "Update Formula E calendar"
            git push
          fi
